name: 🦦 Dr. OtterAI Code Review, PhD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get full history for better context

        - name: 🦦 Dr. OtterAI Code Review, PhD
        uses: fofsinx/OtterAI@1.1.1
            
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: ${{ secrets.OPENAI_BASE_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: 'gpt-4o-mini'
          extra_prompt: |
            Please focus on:
            - Swift best practices
            - Security implications of the changes
            - Performance optimizations
            - Code maintainability and documentation
            - Potential edge cases and error handling 
            - Use emojis in your comments and be very specific.
            - Add code examples in markdown format.