name: Update Bug Report Versions
on:
  push:
    tags:
      - '*'

jobs:
  update-version-dropdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract tag version
        run: echo "NEW_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update issue form
        run: |
          FORM_PATH=".github/ISSUE_TEMPLATE/1-bug-report-form.yml"
          VERSION="$NEW_VERSION"

          if [[ ! -f "$FORM_PATH" ]]; then
            echo "Issue form not found!"
            exit 1
          fi

          # Extract existing versions (lines under options: with ' - x.y')
          mapfile -t versions < <(awk '
            found && /^[[:space:]]+- / { sub(/^[[:space:]]+- /, "", $0); print }
            /id: version/ { found = 1 }
            found && /options:/ { next }
            found && /^[[:space:]]+- / { next }
            found && !/^[[:space:]]+- / { found = 0 }
          ' "$FORM_PATH")

          # Add the new version if it's not already included
          already_included=0
          for v in "${versions[@]}"; do
            if [[ "$v" == "$VERSION" ]]; then
              already_included=1
              break
            fi
          done

          if [[ $already_included -eq 0 ]]; then
            versions+=("$VERSION")
          fi

          # Sort and keep only last 5 versions (descending)
          mapfile -t pruned_versions < <(printf '%s\n' "${versions[@]}" | sort -Vr | head -n 5)

          # Escape versions for YAML
          formatted_versions=$(printf '        - %s\n' "${pruned_versions[@]}")

          # Use awk to replace the options block
          awk -v versions="$formatted_versions" '
            BEGIN { skip = 0 }
            /id: version/ { print; in_version = 1; next }
            in_version && /options:/ {
              print;
              print versions;
              skip = 1;
              next
            }
            skip && /^[[:space:]]+- / { next }
            skip && !/^[[:space:]]+- / { skip = 0 }
            { print }
          ' "$FORM_PATH" > tmp.yml && mv tmp.yml "$FORM_PATH"

      - name: Commit changes
        run: |
          FORM_PATH=".github/ISSUE_TEMPLATE/1-bug-report-form.yml"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add "$FORM_PATH"
            git commit -m "Update issue form: add $NEW_VERSION and prune to last 5 versions"
            git push
          fi
